/*!
 * Copyright (c) 2021 by Contributors
 * \file pass.h
 * \brief Customized MNM passes
 */
#pragma once

#include "mnm/pass.h"

namespace mnm {
namespace pass {

/*!
 * \brief Eliminate the closure in returned value. Replace them with constant 1s.
 * \return The pass.
 */
Pass EliminateClosure();

/*!
 * \brief Wrap identity output values with mnm.op.copy
 * \return The pass.
 */
Pass WrapIdentity();

/*!
 * \brief Canonicalize parameters of the backward closure generated by AutoDiff.
 * \return The pass.
 */
Pass CanonicalizeParamsForRAZOR();

/*!
 * \brief Analyze the IR to get a mapping from output tuple indices to input
 * argument indices that share the same memory (inplace update).
 * \return The pass.
 */
Pass InplaceUpdateAnalysis();

}  // namespace pass
}  // namespace mnm
