# Copyright (c) 2018 Google Inc. All Rights Reserved.
# SPDX-License-Identifier: BSD-3-Clause
# Modifications Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

# Autogenerated file, do not edit!
__version__ = "1.9"
__ltc_gitrev__ = "0e8776b4d45a243df6e8499d070e2df89dcad1f9"
__torch_gitrev__ = "0e8776b4d45a243df6e8499d070e2df89dcad1f9"
