/*
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 * SPDX-License-Identifier: Apache-2.0
 * Modifications Copyright (c) Facebook, Inc.
 */

// Autogenerated file, do not edit!
#include "lazy_tensor_core/csrc/version.h"

namespace torch_lazy_tensors {

const char LTC_GITREV[] = {"0e8776b4d45a243df6e8499d070e2df89dcad1f9"};
const char TORCH_GITREV[] = {"0e8776b4d45a243df6e8499d070e2df89dcad1f9"};

}  // namespace torch_lazy_tensors
