# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

name: CI-Entry-Nightly

on:
  # Since this workflow is triggered by pull requests,
  # we cannot use AWS credential in this workflow. Instead, we trigger
  # another workflow to run the rest CI jobs on AWS batch.
  push:
    branches:
      - 'pt-nightly-compatible**'

defaults:
  run:
    shell: bash

jobs:
  entry:
    if: github.repository == 'awslabs/ratex'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Checkout all branches and history.
      - name: Save common job info
        # Initialize the artifact.
        run: |
          mkdir job_info
          echo "nightly" > job_info/trigger.txt
      - name: Save push event job info
        # Dump the job information.
        # Note that we do not run CI when pushing to pt-nightly-compatible branch.
        if: ${{ github.event_name == 'push' }}
        run: |
          echo "Ref: ${{ github.ref }}"
          echo "Repo: ${{ github.repository }}"
          echo "1" > job_info/skip.txt
          echo "${{ github.ref }}" > job_info/ref.txt
          echo "${{ github.repository }}" > job_info/repo.txt
      - name: Save pull request event job info
        # Dump the job information for running CI with a pull request to pt-nightly-compatible.
        if: ${{ github.event_name == 'pull_request' || github.event_name == 'pull_request_target' }}
        run: |
          echo "0" > job_info/skip.txt
          echo "Ref: ${{ github.event.pull_request.head.ref }}"
          echo "FullName: ${{ github.event.pull_request.head.repo.full_name }}"
          echo "Number: ${{ github.event.number }}"
          echo "HeadSHA: ${{ github.event.pull_request.head.sha }}"
          echo "${{ github.event.pull_request.head.ref }}" > job_info/ref.txt
          echo "${{ github.event.pull_request.head.repo.full_name }}" > job_info/repo.txt
          echo "${{ github.event.number }}" > job_info/pr.txt
          echo "${{ github.event.pull_request.head.sha }}" > job_info/sha.txt
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          path: job_info
          retention-days: 3
