# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

name: Update Submodules
on:
  schedule:
    # Note that cron uses UTC times and weeks start from Sunday (0).
    # RAF updates TVM on Monday, so we update RAF every Friday at 5am (PST).
    - cron:  '0 13 * * 5'

  workflow_dispatch:

jobs:
  update-n-send-PR:
    if: github.repository == 'awslabs/ratex'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Update RAF to the latest commit
      run: |
        git config submodule.syntastic.update "git pull origin main"
        git submodule update --init --remote third_party/raf
    - name: Create timestamp
      id: date
      run: echo "::set-output name=now::$(date +'%Y-%m-%d-%H-%M-%S')"
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.BOT_TOKEN }}
        commit-message: '[RAF] Update Submodule'
        committer: GitHub <noreply@github.com>
        author: AIREMetaBot <aire-meta-bot@users.noreply.github.com>
        branch: update-submodule-raf-${{ steps.date.outputs.now }}
        base: main
        delete-branch: true
        title: '[RAF] Update Submodule ${{ steps.date.outputs.now }}'
        body: |
          _This PR is auto-generated by AIRE Meta Bot._
          
          Please check the CI results before merge it.
          If one or more tests failed, please commit necessary changes to this branch (update-submodule-raf-${{ steps.date.outputs.now }}).
          
          If there are more than one PRs like this, please keep the latest one and manually close others.

        draft: false
